# Generated by Django 4.2.1 on 2023-05-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_avtive',
            new_name='is_active',
        ),
    ]
